### ISSUE TITLE
Ruutu.fi plugin fails in selAvailability[0].string.strip() if len(selAvailability) > 0 else '0' AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by mundic** [szymex/xbmc-finnish-tv#74]
On Ubuntu 14.04.1 LTS & Kodi, ruutu.fi plugin fails with error message you can find here:  http://paste.ubuntu.com/9779261/

**Comment by szymex** [comment]
I committed a potential fix. Can you try it? Just replace ruutu.py in your installation.

**Comment by mundic** [comment]
Hi,
unfortunately fix didn't work. Here are the logs when I used the update: http://paste.ubuntu.com/9788385/

**Comment by mundic** [comment]
By the way plugin worked on Ubuntu 12.04 but when I upgraded to 14.04 this error started.

I spent some time back then looking into this, but didn't figure it out. I wrote about this on Kodi forum back then, there's what I found when investigating this. To me it seems like the html content that the plugin parses differs from the one I get with a browser. I printed out in the log the HTML and there all content was missing

What plugin gets
Code:
<h2 class="node-title">
                                             <a href="/ohjelmat/nfl/1210-live-seattle-seahawks-dallas-cowboys">
                                             </a>
                                            </h2>

And what browser gets
Code:
lass="node-title">

    <a href="/ohjelmat/nfl/1210-live-seattle-seahawks-dallas-cowboys">

        12.10. LIVE Seattle Seahawks - Dallas Cowboys

    </a>

</h2>

The content (title) seems not to be available for the plugin. I don't know what happens there, but when the plugin tries to parse the title it fails. Don't know if this is an environmental issue on my machine or what. Yle Areena and Katsomo plugins work fine.

**Comment by szymex** [comment]
Are you sure you have tested correct file, in you logs it tells: 
```
available = selAvailability[0].string.strip() if len(selAvailability) > 0 else '0'
```
but in a newest file in github that line was changed. You need to manually update ruutu.py from github.

**Comment by mundic** [comment]
Sorry, I think I uploaded an old log file again or something went wrong as when I redid this for some reason kodi.log wan't generated. 

Anyway, after a restart I got the log file and still the plugin fails. Here's the new log file: http://paste.ubuntu.com/9798425/

**Comment by szymex** [comment]
Try again with updated ruutu.py.

**Comment by mundic** [comment]
Thanks, some improvement in this version! 

The good thing is that in this version the menu option ">> Programs" work. I could watch videos under the programs.

Unfortunately Menu options "Latest", "Most Viewed", " News", etc, all fail.

Log available here: http://paste.ubuntu.com/9839122/
- First in the log two failure cases (Latest and Most Viewed, if I recall correctly)
- Later two successful ones. First a program that didn't have any videos and then one that had and the video started.

**Comment by szymex** [comment]
Lets keep trying, try now.

**Comment by mundic** [comment]
Thanks. Some improvement.
Here are the logs: http://paste.ubuntu.com/9865344/

Working:
- Programs - Menu selection
- Most Viewed - Menu selection

Not working:
- Latest
- News
- Sports
- Children
- Food
